name: ipytracer_docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.5
  - traitlets
  - traittypes
  - widgetsnbextension
  - pip:
    - git+https://github.com/sn0wle0pard/ipytracer.git
    - jupyter_sphinx
    - ipywidgets>=6.0.0b6