name: ipytracer_docs
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.5
 - traitlets
 - traittypes
 - widgetsnbextension
 - ipytracer
 - pip:
    - jupyter_sphinx
    - ipywidgets>=6.0.0b6